---
title: "Relationship between Pereived Mental Health and Drug use by Gender"
author: "Yen-Chia Lu(Jerry)"
date: '2022-10-23'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Library Call, echo = FALSE, warning = FALSE, message = FALSE}
library(tinytex)
library(knitr)
library(tidyverse)
library(janitor)
library(mosaic)
library(patchwork)
```

```{r Read Data into R, message = FALSE, warning = FALSE, echo = FALSE}
CCHS <- read_csv("CCHS.csv")
```

```{r Converst Character to Numeric, echo = FALSE, warning = FALSE}
CCHS.Num <- CCHS %>% mutate_if(is.character, as.numeric)
attach(CCHS.Num)
```

```{r Filter, include = FALSE}
## Filtering by 
## Whether or Not Attending School/College/University (1 = Yes, 2 = No)
## Age Range (2 = 15-17, 3 = 18-19, 4 = 20-24, 5 = 25-29)
CCHS.2 <- CCHS.Num %>% filter((MAC_015 == 1 | MAC_015 == 2), (dhhgage > 1 & dhhgage <= 5))
```

```{r, results='asis', eval=(opts_knit$get('rmarkdown.pandoc.to') == 'latex'), echo = FALSE}
cat('\\pagebreak')
```

```{r Freq Distn Tables in CCHS2 Data, include = FALSE}
CCHS.2 %>% 
  count(GEN_015)
CCHS.2 %>% 
  count(drgdvyac)
CCHS.2 <- CCHS.2 %>% drop_na(GEN_015, drgdvyac)
CCHS.2 %>% 
  count(GEN_015)
CCHS.2 %>% 
  count(drgdvyac)
```

```{r, results='asis', eval=(opts_knit$get('rmarkdown.pandoc.to') == 'latex'), echo = FALSE}
cat('\\pagebreak')
```

```{r Re-level Variables, include = FALSE}
# Perceived Mental Health:
# Yes as Excellent, Very Good, Good; No as Fair or Poor
# Drug use
# Strong as Very Strong, or Somewhat Strong; No as Somewhat Weak or Very Weak 
CCHS.2 <- CCHS.2 %>% 
  mutate(Positive.Mental.Health = case_when(GEN_015 <= 3 ~ "Yes", 
                                            GEN_015 >= 4 ~ "No"), 
         Drug.use = case_when(drgdvyac <=1 ~ "negative",
                                     GEN_030 >= 2 ~ "positive "),
          Gender = case_when(DHH_SEX == 1 ~ "Male", 
                            DHH_SEX == 2 ~ "Female"))
```

```{r, results='asis', eval=(opts_knit$get('rmarkdown.pandoc.to') == 'latex'), echo = FALSE}
cat('\\pagebreak')
```

### Contingency Table for Perceived Mental Health and Drug use
```{r TwoWay Table using Different R Packages, echo = FALSE}

# Two-way Table using {janitor} package
# data frame
CCHS.2 %>%                                  
  # cross-tabulate counts of two columns
  tabyl(Drug.use, Perceived.Mental.Health) %>%            
  # add a total row, add a total column
  adorn_totals(where = c("row", "col")) %>% 
  # convert to proportions with row denominator
  adorn_percentages(denominator = "row") %>% 
  # convert proportions to percents
  adorn_pct_formatting() %>%  
  # display as: "count (percent)"
  adorn_ns(position = "front") %>% 
  # adjust titles
  adorn_title(                                
    row_name = "Drug use",
    col_name = "Perceived Mental Health") %>%
  # print elegant results for interactive analysis or for sharing in a report
  # e.g., with knitr::kable()
  knitr::kable()


```

```{r, results='asis', eval=(opts_knit$get('rmarkdown.pandoc.to') == 'latex'), echo = FALSE}
cat('\\pagebreak')
```

### Contingency Table for Mental Health and Gender
```{r TwoWayTable using Different R Packages, echo = FALSE}

# Two-way Table using {janitor} package
# data frame
CCHS.2 %>%                                  
  # cross-tabulate counts of two columns
  tabyl(Gender, Perceived.Mental.Health) %>%            
  # add a total row, add a total column
  adorn_totals(where = c("row", "col")) %>% 
  # convert to proportions with row denominator
  adorn_percentages(denominator = "row") %>% 
  # convert proportions to percents
  adorn_pct_formatting() %>%  
  # display as: "count (percent)"
  adorn_ns(position = "front") %>% 
  # adjust titles
  adorn_title(                                
    row_name = "Gender",
    col_name = "Perceived Mental Health") %>%
  # print elegant results for interactive analysis or for sharing in a report
  # e.g., with knitr::kable()
  knitr::kable()


```

```{r, results='asis', eval=(opts_knit$get('rmarkdown.pandoc.to') == 'latex'), echo = FALSE}
cat('\\pagebreak')
```

### Bivariate Association: Bar Plots
```{r Bar Plot of Data, echo = FALSE}

# Bar Plots of Perceived Mental Health and Drug use
bar.plot1 = ggplot(CCHS.2, aes(x = factor(Perceived.Mental.Health), fill = factor(Drug.use))) 
bar.plot1 = bar.plot1 + geom_bar(position = "dodge")
bar.plot1 = bar.plot1 + labs(fill = "Drug use")
bar.plot1 = bar.plot1 + xlab("Perceived Mental Health") 
bar.plot1 = bar.plot1 + ylab("Count")

# Bar Plots of Positive Mental Health and Gender
bar.plot2 = ggplot(CCHS.2, aes(x = factor(Perceived.Mental.Health), fill = factor(Gender))) 
bar.plot2 = bar.plot2 + geom_bar(position = "dodge")
bar.plot2 = bar.plot2 + labs(fill = "Gender")
bar.plot2 = bar.plot2 + xlab("Perceived Mental Health") 
bar.plot2 = bar.plot2 + ylab("Count")

bar.plot1 + bar.plot2 
```

```{r, results='asis', eval=(opts_knit$get('rmarkdown.pandoc.to') == 'latex'), echo = FALSE}
cat('\\pagebreak')
```
                    

### Multivariate Association
```{r ThreeWay Table using janitor R Package, echo = FALSE}
# data frame
CCHS.2 %>%                                  
  # cross-tabulate counts of two columns
  tabyl(Drug.use, perceived.Mental.Health, Gender) %>%            
  # add a total row, add a total column
  adorn_totals(where = c("row", "col")) %>% 
  # convert to proportions with row denominator
  adorn_percentages(denominator = "row") %>% 
  # convert proportions to percents
  adorn_pct_formatting() %>%  
  # display as: "count (percent)"
  adorn_ns(position = "front") %>% 
  # adjust titles
  adorn_title(                                
    row_name = "Drug use",
    col_name = "Perceived Mental Health") %>%
  # print elegant results for interactive analysis or for sharing in a report
  # e.g., with knitr::kable()
  knitr::kable()
```

```{r, results='asis', eval=(opts_knit$get('rmarkdown.pandoc.to') == 'latex'), echo = FALSE}
cat('\\pagebreak')
```

```{r ThreeWay Table using mosaic R Package, include = FALSE}
tally(~ Perceived.Mental.Health | Drug.use + Gender, 
      margin = TRUE, data = CCHS.2)
tally(~ Perceived.Mental.Health | Drug.use + Gender, 
      margin = TRUE, format = "percent", data = CCHS.2)
```

```{r, results='asis', eval=(opts_knit$get('rmarkdown.pandoc.to') == 'latex'), echo = FALSE}
cat('\\pagebreak')
```

```{r Multivariate Bar Plots, echo=FALSE}
# Side-by-side Bar Plots: Multivariate Association
bar.plot = ggplot(CCHS.2, aes(x = factor(Perceived.Mental.Health), fill = factor(Drug.use))) 
bar.plot = bar.plot + geom_bar(position = "dodge")
bar.plot = bar.plot + labs(fill = "Drug use")
bar.plot = bar.plot + xlab("Perceived Mental Health") 
bar.plot = bar.plot + ggtitle("Bar Plots of Perceived Mental Health and Drug use by Gender")
bar.plot = bar.plot + facet_wrap(~factor(Gender), scales = "free_x")
bar.plot = bar.plot + theme_bw()
bar.plot
```
